### ISSUE TITLE
[Feature Suggestion] Allow to toggle the background per individual pin

### ISSUE THREAD

**Issue by Nova-Katt** [schultzcole/FVTT-Backgroundless-Pins#1]
Hi! Lovely mod, but I keep turning it on and off all the time because of one issue.
It's all or nothing. No background on any pins, or background on all pins.

Depending on the type of map note, I might sometimes want the background, and sometimes I do not want the background, so it would be amazing if this module, instead of just turning them off for all map notes, also allow us to toggle it back on, per map note.

This would be incredibly handy since I often use the icons from that game-icons site, and they often look best with their white color, transparent background, on top of the default semi-transparent foundry map note background.
While some other stuff, like if I'm dropping an item, a letter, or marking a city (like in your gif preview), then it looks better with the default background off.

So yeah, would be nice to be able to choose per pin instead of all or nothing. :)

Cheers!

**Comment by schultzcole** [comment]
Thanks for the request! I have added this in Backgroundless Pins 1.2.0, please try it out (though note that it is currently only compatible with core version 0.7.3)

**Comment by Nova-Katt** [comment]
OH, great to hear, but I can't test it since you made the update Beta exclusive, and I'm running Stable 0.6.6 because for now, there are just too many bugs to use beta when running a lot of modules. ^^' so I guess I'll have something to look forward to when 0.7 becomes stable. :P
